/**
 * Banco de 200 perguntas do Quiz Bíblico, extraídas do PDF "Quiz Bíblico -
 * 200 perguntas e respostas" (Mateus Eleutério), licenciado pessoalmente
 * para o dono deste app. Organizadas nos mesmos 4 níveis já usados pela
 * tela de Quiz (facil, intermediario, dificil, expert), 50 por nível,
 * exatamente como no PDF original.
 *
 * Cada item tem:
 *  - numero: número da pergunta dentro do seu nível no PDF original
 *  - nivel: facil | intermediario | dificil | expert
 *  - pergunta / resposta: texto literal do PDF
 *  - referencia_biblica: citação bíblica dada no PDF (quando existe)
 *
 * Usado apenas por QuizQuestionImporter.jsx para popular a entidade
 * QuizQuestion uma única vez - não é lido diretamente pela tela de Quiz.
 */

export const QUIZ_SEED_DATA = [
  // ===== FÁCIL =====
  { numero: 1, nivel: "facil", pergunta: "Quem construiu a arca?", resposta: "Noé", referencia_biblica: "Gênesis 6:14-22" },
  { numero: 2, nivel: "facil", pergunta: "Quantos dias e noites choveu durante o dilúvio?", resposta: "Quarenta dias e quarenta noites", referencia_biblica: "Gênesis 7:12, 7:17" },
  { numero: 3, nivel: "facil", pergunta: "Quem foi engolido por um grande peixe?", resposta: "Jonas", referencia_biblica: "Jonas 1:17" },
  { numero: 4, nivel: "facil", pergunta: "Qual o nome do primeiro casal?", resposta: "Adão e Eva", referencia_biblica: "Gênesis 2:4-25" },
  { numero: 5, nivel: "facil", pergunta: "Quem foi o primeiro assassino mencionado na Bíblia?", resposta: "Caim", referencia_biblica: "Gênesis 4:8" },
  { numero: 6, nivel: "facil", pergunta: "Qual montanha Moisés recebeu os Dez Mandamentos?", resposta: "Monte Sinai", referencia_biblica: "Êxodo 34:28-29" },
  { numero: 7, nivel: "facil", pergunta: "Qual é o primeiro livro da Bíblia?", resposta: "Gênesis", referencia_biblica: "" },
  { numero: 8, nivel: "facil", pergunta: "Quem matou Golias?", resposta: "Davi", referencia_biblica: "1 Samuel 17:49-51" },
  { numero: 9, nivel: "facil", pergunta: "Qual animal falou com Balaão?", resposta: "Uma jumenta", referencia_biblica: "Números 22:28" },
  { numero: 10, nivel: "facil", pergunta: "Quem foi transformado em uma estátua de sal?", resposta: "A esposa de Ló", referencia_biblica: "Gênesis 19:26" },
  { numero: 11, nivel: "facil", pergunta: "Quem foi lançado na cova dos leões?", resposta: "Daniel", referencia_biblica: "Daniel 6:16-23" },
  { numero: 12, nivel: "facil", pergunta: "Quem eram os pais terrenos de Jesus?", resposta: "Maria e José", referencia_biblica: "Mateus 1:18-25" },
  { numero: 13, nivel: "facil", pergunta: "Qual foi o primeiro milagre de Jesus?", resposta: "Transformar água em vinho", referencia_biblica: "João 2:1-11" },
  { numero: 14, nivel: "facil", pergunta: "Quem traiu Jesus por 30 moedas de prata?", resposta: "Judas Iscariotes", referencia_biblica: "Mateus 26:14-16" },
  { numero: 15, nivel: "facil", pergunta: "Quem negou Jesus três vezes?", resposta: "Pedro", referencia_biblica: "Mateus 26:74-75" },
  { numero: 16, nivel: "facil", pergunta: "Quem foi salvo na cidade de Sodoma?", resposta: "Ló", referencia_biblica: "Gênesis 19:15-17" },
  { numero: 17, nivel: "facil", pergunta: "Qual é o último livro da Bíblia?", resposta: "Apocalipse", referencia_biblica: "" },
  { numero: 18, nivel: "facil", pergunta: "Quem escreveu muitos Salmos?", resposta: "Davi (73 salmos)", referencia_biblica: "" },
  { numero: 19, nivel: "facil", pergunta: "Quem era o rei mais sábio de Israel?", resposta: "Salomão", referencia_biblica: "1 Reis 3:12-15" },
  { numero: 20, nivel: "facil", pergunta: "Em qual rio Jesus foi batizado?", resposta: "Rio Jordão", referencia_biblica: "Mateus 3:13-17" },
  { numero: 21, nivel: "facil", pergunta: "Quem foi salvo da morte por sua mãe ao ser colocado em um cesto na beira do rio?", resposta: "Moisés", referencia_biblica: "Êxodo 2:10" },
  { numero: 22, nivel: "facil", pergunta: "Quem liderou os israelitas para fora do Egito?", resposta: "Moisés", referencia_biblica: "Êxodo 3:10-12" },
  { numero: 23, nivel: "facil", pergunta: "Em que cidade Jesus nasceu?", resposta: "Belém", referencia_biblica: "Mateus 2:1" },
  { numero: 24, nivel: "facil", pergunta: "Quem foi o irmão mais novo de José?", resposta: "Benjamim", referencia_biblica: "Gênesis 35:16-18" },
  { numero: 25, nivel: "facil", pergunta: "Quem foi o discípulo que duvidou da ressurreição de Jesus até vê-Lo?", resposta: "Tomé", referencia_biblica: "João 20:24-29" },
  { numero: 26, nivel: "facil", pergunta: "Qual é o segundo livro da Bíblia?", resposta: "Êxodo", referencia_biblica: "" },
  { numero: 27, nivel: "facil", pergunta: "Quem lutou com um anjo e teve seu nome mudado para Israel?", resposta: "Jacó", referencia_biblica: "Gênesis 35:10" },
  { numero: 28, nivel: "facil", pergunta: "Qual é o nome do jardim onde Adão e Eva viviam?", resposta: "Éden", referencia_biblica: "Gênesis 2:8" },
  { numero: 29, nivel: "facil", pergunta: "Quando Jesus nasceu, onde Ele foi colocado?", resposta: "Manjedoura", referencia_biblica: "Lucas 2:16" },
  { numero: 30, nivel: "facil", pergunta: "Quantas pragas foram enviadas ao Egito?", resposta: "10 pragas", referencia_biblica: "Êxodo 7 a 10" },
  { numero: 31, nivel: "facil", pergunta: "Quem cortou o cabelo de Sansão?", resposta: "Dalila", referencia_biblica: "Juízes 16:18-19" },
  { numero: 32, nivel: "facil", pergunta: "Qual livro da Bíblia relata a saída dos israelitas do Egito?", resposta: "Livro de Êxodo", referencia_biblica: "" },
  { numero: 33, nivel: "facil", pergunta: "Jesus comparou o Reino de Deus a qual semente?", resposta: "Ao grão de mostarda", referencia_biblica: "Mateus 13:31-32" },
  { numero: 34, nivel: "facil", pergunta: "Quem encontrou um bebê em um cesto na beira do rio Nilo?", resposta: "A filha do Faraó", referencia_biblica: "Êxodo 2:1-10" },
  { numero: 35, nivel: "facil", pergunta: "Quem foi o profeta que orou e Deus fez o sol parar?", resposta: "Josué", referencia_biblica: "Josué 10:12-14" },
  { numero: 36, nivel: "facil", pergunta: "Quem foi o rei que teve um sonho sobre sete vacas magras e sete vacas gordas?", resposta: "Faraó", referencia_biblica: "Gênesis 41:17" },
  { numero: 37, nivel: "facil", pergunta: "Quem era o amigo especial de Davi?", resposta: "Jônatas", referencia_biblica: "1 Samuel 18:1-4" },
  { numero: 38, nivel: "facil", pergunta: "Quem foi o juiz de Israel que não podia cortar o cabelo?", resposta: "Sansão", referencia_biblica: "Juízes 13:5 e 24" },
  { numero: 39, nivel: "facil", pergunta: "Quem era o governador que lavou as mãos durante o julgamento de Jesus?", resposta: "Pôncio Pilatos", referencia_biblica: "Mateus 27:22-24" },
  { numero: 40, nivel: "facil", pergunta: "Em que livro da Bíblia se encontra a história da criação?", resposta: "Gênesis", referencia_biblica: "Gênesis 1:1" },
  { numero: 41, nivel: "facil", pergunta: "Quem foi o Rei que construiu o primeiro templo em Jerusalém?", resposta: "Salomão", referencia_biblica: "1 Reis 6:1" },
  { numero: 42, nivel: "facil", pergunta: "Quem foi o discípulo que andou sobre a água, mas começou a afundar?", resposta: "Pedro", referencia_biblica: "Mateus 14:28-29" },
  { numero: 43, nivel: "facil", pergunta: "Quem foi o profeta que não morreu, mas foi levado ao céu num redemoinho?", resposta: "Elias", referencia_biblica: "2 Reis 2:11" },
  { numero: 44, nivel: "facil", pergunta: "Quem escreveu a maioria das cartas do Novo Testamento?", resposta: "Paulo", referencia_biblica: "" },
  { numero: 45, nivel: "facil", pergunta: "Quem era o homem mais forte da Bíblia?", resposta: "Sansão", referencia_biblica: "Juízes 14:6; 15:15; 16:3; 16:29-30" },
  { numero: 46, nivel: "facil", pergunta: "Quem era o cobrador de impostos que subiu em uma árvore para ver Jesus?", resposta: "Zaqueu", referencia_biblica: "Lucas 19:3-6" },
  { numero: 47, nivel: "facil", pergunta: 'Qual era o nome da comida que "caía do céu" para alimentar os israelitas?', resposta: "Maná", referencia_biblica: "Êxodo 16:14-20" },
  { numero: 48, nivel: "facil", pergunta: "Em que livro da Bíblia está a história de Noé?", resposta: "Gênesis", referencia_biblica: "" },
  { numero: 49, nivel: "facil", pergunta: "Quem recebeu a promessa de ter descendentes tão numerosos quanto as estrelas do céu?", resposta: "Abraão", referencia_biblica: "Gênesis 15:5-6" },
  { numero: 50, nivel: "facil", pergunta: "Jesus entrou em Jerusalém montado em que animal?", resposta: "Jumento", referencia_biblica: "Mateus 21:5" },

  // ===== INTERMEDIÁRIO =====
  { numero: 1, nivel: "intermediario", pergunta: "Quem foi o profeta que desafiou a rainha Jezabel?", resposta: "Elias", referencia_biblica: "1 Reis 21:17-24" },
  { numero: 2, nivel: "intermediario", pergunta: "Qual é o nome da mulher de Isaque?", resposta: "Rebeca", referencia_biblica: "Gênesis 24:66" },
  { numero: 3, nivel: "intermediario", pergunta: "Quem era o pai de José, que deu uma túnica de muitas cores?", resposta: "Jacó (Israel)", referencia_biblica: "Gênesis 37:3" },
  { numero: 4, nivel: "intermediario", pergunta: "Qual o nome do anjo que anunciou o nascimento de Jesus a Maria?", resposta: "Anjo Gabriel", referencia_biblica: "Lucas 1:26-38" },
  { numero: 5, nivel: "intermediario", pergunta: "Quem foi o rei de Israel após a morte de Saul?", resposta: "Davi", referencia_biblica: "2 Samuel 2:6-7" },
  { numero: 6, nivel: "intermediario", pergunta: "Qual dos irmãos de José foi mantido no Egito enquanto os outros retornavam?", resposta: "Simeão", referencia_biblica: "Gênesis 42:24" },
  { numero: 7, nivel: "intermediario", pergunta: "Quem foram os dois primeiros discípulos chamados por Jesus?", resposta: "Simão Pedro e André", referencia_biblica: "Mateus 4:18-20; Marcos 1:16-18" },
  { numero: 8, nivel: "intermediario", pergunta: "Qual é o nome do homem que foi o primeiro a ser circuncidado?", resposta: "Abraão", referencia_biblica: "Gênesis 17:9-23" },
  { numero: 9, nivel: "intermediario", pergunta: "Qual era o nome da mulher que ungiu os pés de Jesus com um perfume caro e os enxugou com seus cabelos?", resposta: "Maria, de Betânia", referencia_biblica: "João 12:1-8" },
  { numero: 10, nivel: "intermediario", pergunta: "Quem foi o profeta que sucedeu Elias?", resposta: "Eliseu", referencia_biblica: "2 Reis 2:9-15" },
  { numero: 11, nivel: "intermediario", pergunta: "Qual é o nome da irmã de Arão?", resposta: "Miriã", referencia_biblica: "Êxodo 15:20" },
  { numero: 12, nivel: "intermediario", pergunta: "Quem vendeu sua primogenitura por um prato de lentilha?", resposta: "Esaú", referencia_biblica: "Gênesis 25:29-34" },
  { numero: 13, nivel: "intermediario", pergunta: "Qual o nome do poço onde Jesus falou com a mulher samaritana?", resposta: "Poço de Jacó", referencia_biblica: "João 4:6" },
  { numero: 14, nivel: "intermediario", pergunta: "Qual cidade foi o local de nascimento de Paulo?", resposta: "Tarso", referencia_biblica: "Atos 22:3" },
  { numero: 15, nivel: "intermediario", pergunta: "Quem foi o sacerdote que pensou que Ana estava embriagada enquanto ela orava?", resposta: "Sacerdote Eli", referencia_biblica: "1 Samuel 1:12-14" },
  { numero: 16, nivel: "intermediario", pergunta: "Qual é o salmo mais longo da Bíblia?", resposta: "Salmo 119", referencia_biblica: "" },
  { numero: 17, nivel: "intermediario", pergunta: "Quem era o irmão de Maria e Marta que Jesus ressuscitou?", resposta: "Lázaro", referencia_biblica: "João 11:1" },
  { numero: 18, nivel: "intermediario", pergunta: "Qual discípulo substituiu Judas Iscariotes?", resposta: "Matias", referencia_biblica: "Atos 1:26" },
  { numero: 19, nivel: "intermediario", pergunta: "Quem foi o rei que ordenou a matança de todos os bebês meninos em Belém?", resposta: "Herodes, o Grande", referencia_biblica: "Mateus 2:16" },
  { numero: 20, nivel: "intermediario", pergunta: "Quem foi o rei que fez um decreto para que os judeus do cativeiro babilônico retornassem a Jerusalém?", resposta: "Ciro, rei da Pérsia", referencia_biblica: "Esdras 1:1-4" },
  { numero: 21, nivel: "intermediario", pergunta: "Qual é o maior mandamento, segundo Jesus?", resposta: "Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma e de todo o seu entendimento.", referencia_biblica: "Mateus 22:36-38" },
  { numero: 22, nivel: "intermediario", pergunta: 'Quem foi o discípulo conhecido como "o discípulo amado"?', resposta: "João", referencia_biblica: "João 13:23" },
  { numero: 23, nivel: "intermediario", pergunta: "Quem são conhecidos como os patriarcas na Bíblia?", resposta: "Abraão, Isaque e Jacó", referencia_biblica: "Êxodo 3:6" },
  { numero: 24, nivel: "intermediario", pergunta: "Por quantos dias Lázaro permaneceu morto antes de Jesus ressuscitá-lo?", resposta: "Quatro dias", referencia_biblica: "João 11:39" },
  { numero: 25, nivel: "intermediario", pergunta: "Qual instrumento Davi tocava?", resposta: "Harpa", referencia_biblica: "1 Samuel 16:23" },
  { numero: 26, nivel: "intermediario", pergunta: "Na primeira multiplicação dos pães e peixes realizada por Jesus, quantos pães e peixes o jovem trouxe?", resposta: "Cinco pães e dois peixes", referencia_biblica: "João 6:9" },
  { numero: 27, nivel: "intermediario", pergunta: "Qual era a doença do homem que foi baixado pelo teto para ser curado por Jesus?", resposta: "Paralítico", referencia_biblica: "Marcos 2:3-4" },
  { numero: 28, nivel: "intermediario", pergunta: "Qual o nome do sacerdote que criou Samuel?", resposta: "Eli", referencia_biblica: "1 Samuel 1:25-28" },
  { numero: 29, nivel: "intermediario", pergunta: "Quem eram os pais de João Batista?", resposta: "Isabel e Zacarias", referencia_biblica: "Lucas 1:13" },
  { numero: 30, nivel: "intermediario", pergunta: "Qual o nome do homem que ajudou Jesus a carregar a cruz?", resposta: "Simão de Cirene", referencia_biblica: "Mateus 27:32" },
  { numero: 31, nivel: "intermediario", pergunta: "O que Jesus misturou para curar um homem cego?", resposta: "Misturou saliva com terra", referencia_biblica: "João 9:6" },
  { numero: 32, nivel: "intermediario", pergunta: "Quem escreveu o livro de Provérbios?", resposta: "Salomão", referencia_biblica: "Provérbios 1:1" },
  { numero: 33, nivel: "intermediario", pergunta: "Quem foi a rainha que salvou seu povo de um plano para destruí-los?", resposta: "Ester", referencia_biblica: "Livro de Ester" },
  { numero: 34, nivel: "intermediario", pergunta: "Qual é o maior livro da Bíblia?", resposta: "Salmos (150 capítulos)", referencia_biblica: "" },
  { numero: 35, nivel: "intermediario", pergunta: "Qual é o nome do homem mais velho mencionado na Bíblia?", resposta: "Matusalém", referencia_biblica: "Gênesis 5:27" },
  { numero: 36, nivel: "intermediario", pergunta: "Qual é o nome do monte onde Noé repousou a arca?", resposta: "Monte Ararate", referencia_biblica: "Gênesis 8:4" },
  { numero: 37, nivel: "intermediario", pergunta: "Quem era o rei de Salém que abençoou Abraão?", resposta: "Melquisedeque", referencia_biblica: "Gênesis 14:18-19" },
  { numero: 38, nivel: "intermediario", pergunta: 'Quantos livros são conhecidos como "profetas menores"?', resposta: "Doze (os doze últimos livros do Antigo Testamento)", referencia_biblica: "" },
  { numero: 39, nivel: "intermediario", pergunta: "Qual é o nome do rio onde Naamã foi curado de lepra?", resposta: "Rio Jordão", referencia_biblica: "2 Reis 5:9-10" },
  { numero: 40, nivel: "intermediario", pergunta: "Quem era o irmão mais novo de Caim?", resposta: "Abel", referencia_biblica: "Gênesis 4:1-2" },
  { numero: 41, nivel: "intermediario", pergunta: "Qual é o nome do lugar onde Jesus orou antes de ser traído?", resposta: "Getsêmani", referencia_biblica: "Mateus 26:36" },
  { numero: 42, nivel: "intermediario", pergunta: "Quem era o pai de Salomão?", resposta: "Davi", referencia_biblica: "2 Samuel 12:24" },
  { numero: 43, nivel: "intermediario", pergunta: "Quem foi o rei que tentou matar Davi várias vezes?", resposta: "Saul", referencia_biblica: "1 Samuel 18:10-11" },
  { numero: 44, nivel: "intermediario", pergunta: "Quem foi o homem que andou com Deus e não foi mais visto, porque Deus o levou para junto de si?", resposta: "Enoque", referencia_biblica: "Gênesis 5:24" },
  { numero: 45, nivel: "intermediario", pergunta: "Qual é o nome do profeta que escreveu sobre a visão do vale de ossos secos?", resposta: "Ezequiel", referencia_biblica: "Ezequiel 37:1-14" },
  { numero: 46, nivel: "intermediario", pergunta: "Por quanto tempo Moisés e o povo hebreu ficaram no deserto?", resposta: "40 anos", referencia_biblica: "Números 14:33-34" },
  { numero: 47, nivel: "intermediario", pergunta: "O que a mulher tinha que foi curada ao tocar na veste de Jesus?", resposta: "Hemorragia (fluxo de sangue intenso)", referencia_biblica: "Mateus 9:20-22" },
  { numero: 48, nivel: "intermediario", pergunta: "Quem foi o discípulo que, durante a Última Ceia, perguntou a Jesus quem o trairia?", resposta: "João", referencia_biblica: "João 13:23-25" },
  { numero: 49, nivel: "intermediario", pergunta: "Quem foi o rei que se arrependeu depois de ouvir o profeta Natã?", resposta: "Davi", referencia_biblica: "2 Samuel 12:13" },
  { numero: 50, nivel: "intermediario", pergunta: "Como era o nome da ilha que João estava quando teve a visão do Apocalipse?", resposta: "Patmos", referencia_biblica: "Apocalipse 1:9" },

  // ===== DIFÍCIL =====
  { numero: 1, nivel: "dificil", pergunta: "Qual profeta foi alimentado por corvos?", resposta: "Elias", referencia_biblica: "1 Reis 17:2-6" },
  { numero: 2, nivel: "dificil", pergunta: "Quem teve um sonho sobre uma escada cujo topo atingia o céu, e os anjos de Deus subiam e desciam por ela?", resposta: "Jacó", referencia_biblica: "Gênesis 28:10-12" },
  { numero: 3, nivel: "dificil", pergunta: "Qual era o nome hebraico de Ester?", resposta: "Hadassa", referencia_biblica: "Ester 2:7" },
  { numero: 4, nivel: "dificil", pergunta: "Quem escreveu o livro de Lamentações?", resposta: "Jeremias", referencia_biblica: "Lamentações 1:1" },
  { numero: 5, nivel: "dificil", pergunta: "Qual é o nome da montanha onde Abraão foi ordenado a sacrificar Isaque?", resposta: "Monte Moriá", referencia_biblica: "Gênesis 22:2" },
  { numero: 6, nivel: "dificil", pergunta: "Quem substituiu Moisés como líder dos israelitas?", resposta: "Josué", referencia_biblica: "Deuteronômio 31:14, 34:9" },
  { numero: 7, nivel: "dificil", pergunta: "Quem era o marido de Priscila, um casal mencionado várias vezes no Novo Testamento?", resposta: "Áquila", referencia_biblica: "Atos 18:2; Romanos 16:3" },
  { numero: 8, nivel: "dificil", pergunta: "Quem foi o rei que, de acordo com o Livro de Daniel, viu uma mão escrevendo na parede durante um banquete real?", resposta: "Belsazar", referencia_biblica: "Daniel 5:1" },
  { numero: 9, nivel: "dificil", pergunta: "Qual é o fruto do Espírito mencionado por Paulo?", resposta: "Amor, Alegria, Paz, Paciência/longanimidade, Amabilidade/benignidade, Bondade, Fidelidade, Mansidão, Domínio próprio", referencia_biblica: "Gálatas 5:22-23" },
  { numero: 10, nivel: "dificil", pergunta: "Quem foi o profeta que falou com Deus em uma caverna?", resposta: "Elias", referencia_biblica: "1 Reis 19:9" },
  { numero: 11, nivel: "dificil", pergunta: "Qual é o nome da profetisa que ajudou a liderar Israel no tempo dos juízes?", resposta: "Débora", referencia_biblica: "Juízes 4:4" },
  { numero: 12, nivel: "dificil", pergunta: "Qual o nome do profeta que casou com uma prostituta a pedido de Deus?", resposta: "Oseias", referencia_biblica: "Oseias 1:2-3" },
  { numero: 13, nivel: "dificil", pergunta: "Quem foi o homem, que ficou mudo durante a gravidez de sua esposa até o nascimento do filho?", resposta: "Zacarias", referencia_biblica: "Lucas 1:18-20" },
  { numero: 14, nivel: "dificil", pergunta: "Quem foi a rainha que visitou o rei Salomão para testar sua sabedoria com enigmas e profecias?", resposta: "Rainha de Sabá", referencia_biblica: "1 Reis 10:1" },
  { numero: 15, nivel: "dificil", pergunta: "Quem foi o filho de Davi que o traiu?", resposta: "Absalão", referencia_biblica: "2 Samuel 15:1" },
  { numero: 16, nivel: "dificil", pergunta: "Quem era a mulher cananeia que escondeu espiões israelitas?", resposta: "Raabe", referencia_biblica: "Josué 2:3" },
  { numero: 17, nivel: "dificil", pergunta: 'Qual o nome do cego que clamou "Jesus, filho de Davi, tem misericórdia de mim"?', resposta: "Bartimeu", referencia_biblica: "Marcos 10:46-48" },
  { numero: 18, nivel: "dificil", pergunta: "Quem apareceu no monte da transfiguração junto com Jesus?", resposta: "Moisés e Elias", referencia_biblica: "Mateus 17:3" },
  { numero: 19, nivel: "dificil", pergunta: "Quem era o bisavô de Davi?", resposta: "Boaz", referencia_biblica: "Rute 4:17-22" },
  { numero: 20, nivel: "dificil", pergunta: "Quem foi o profeta que escreveu sobre a visão dos quatro animais e o Filho do Homem?", resposta: "Daniel", referencia_biblica: "Daniel 7:1-2" },
  { numero: 21, nivel: "dificil", pergunta: "Qual discípulo, também conhecido como Levi, era um coletor de impostos antes de seguir Jesus?", resposta: "Mateus", referencia_biblica: "Mateus 9:9" },
  { numero: 22, nivel: "dificil", pergunta: "Quem foi o juiz que lutou contra os midianitas com apenas 300 homens?", resposta: "Gideão", referencia_biblica: "Juízes 7:7" },
  { numero: 23, nivel: "dificil", pergunta: "Qual é o nome do lugar onde Jacó lutou com Deus?", resposta: "Peniel", referencia_biblica: "Gênesis 32:30" },
  { numero: 24, nivel: "dificil", pergunta: "Quem foi a mulher que pediu a cabeça de João Batista?", resposta: "A filha de Herodias", referencia_biblica: "Marcos 6:22-24" },
  { numero: 25, nivel: "dificil", pergunta: "Qual rei, ao encontrar o livro da lei no templo, respondeu com grande pesar e, posteriormente, liderou uma reforma religiosa em Judá?", resposta: "Rei Josias", referencia_biblica: "2 Crônicas 34:33" },
  { numero: 26, nivel: "dificil", pergunta: "Qual profeta teve uma visão das águas que fluíam do templo?", resposta: "Ezequiel", referencia_biblica: "Ezequiel 47:1-12" },
  { numero: 27, nivel: "dificil", pergunta: "Qual é o nome da montanha onde Moisés viu a Terra Prometida, mas não entrou?", resposta: "Monte Nebo", referencia_biblica: "Deuteronômio 34:1" },
  { numero: 28, nivel: "dificil", pergunta: "Quem foi o rei que se casou com 700 princesas e também teve 300 concubinas?", resposta: "Salomão", referencia_biblica: "1 Reis 11:2-3" },
  { numero: 29, nivel: "dificil", pergunta: "Quem foi o primeiro mártir cristão?", resposta: "Estêvão", referencia_biblica: "Atos 7:54-60" },
  { numero: 30, nivel: "dificil", pergunta: "Qual é o nome da esposa de Boaz?", resposta: "Rute", referencia_biblica: "Rute 4:13" },
  { numero: 31, nivel: "dificil", pergunta: "Qual era o nome babilônico de Daniel?", resposta: "Beltesazar", referencia_biblica: "Daniel 1:7" },
  { numero: 32, nivel: "dificil", pergunta: "Qual é o nome do irmão de Moisés que também foi seu porta-voz?", resposta: "Arão", referencia_biblica: "Êxodo 4:14-16" },
  { numero: 33, nivel: "dificil", pergunta: "Quem teve seu corpo disputado pelo arcanjo Miguel e o Diabo?", resposta: "Moisés", referencia_biblica: "Judas 1:9" },
  { numero: 34, nivel: "dificil", pergunta: "Qual era o nome dos filhos de Arão que colocaram fogo estranho no altar?", resposta: "Nadabe e Abiú", referencia_biblica: "Levítico 10:1" },
  { numero: 35, nivel: "dificil", pergunta: "Qual foi o profeta que andou nu por 3 anos?", resposta: "Isaías", referencia_biblica: "Isaías 20:2-4" },
  { numero: 36, nivel: "dificil", pergunta: "Qual era a nacionalidade de Rute?", resposta: "Moabita", referencia_biblica: "Rute 1:4" },
  { numero: 37, nivel: "dificil", pergunta: "Quem foi o rei que perdeu sua sanidade e viveu como um animal?", resposta: "Nabucodonosor", referencia_biblica: "Daniel 4:33" },
  { numero: 38, nivel: "dificil", pergunta: "Qual é o nome dos homens que foram lançados na fornalha ardente?", resposta: "Sadraque, Mesaque e Abede-Nego", referencia_biblica: "Daniel 3:20" },
  { numero: 39, nivel: "dificil", pergunta: "Quem foi o profeta que repreendeu o rei Davi pelo seu pecado com Bate-Seba?", resposta: "Natã", referencia_biblica: "2 Samuel 12:1" },
  { numero: 40, nivel: "dificil", pergunta: "Qual é o nome do homem que foi enganado por seus filhos a pensar que seu filho favorito estava morto?", resposta: "Jacó", referencia_biblica: "Gênesis 37:31-35" },
  { numero: 41, nivel: "dificil", pergunta: "Quem foi o rei que teve um sonho sobre uma estátua com cabeça de ouro e pés em parte de barro?", resposta: "Nabucodonosor", referencia_biblica: "Daniel 2:45-46" },
  { numero: 42, nivel: "dificil", pergunta: "Qual é o nome do filho de Raquel que foi vendido como escravo por seus irmãos?", resposta: "José", referencia_biblica: "Gênesis 37:28" },
  { numero: 43, nivel: "dificil", pergunta: "Quem foi o profeta que enfrentou os profetas de Baal no Monte Carmelo?", resposta: "Elias", referencia_biblica: "1 Reis 18:40" },
  { numero: 44, nivel: "dificil", pergunta: "Qual é o nome do lugar onde Paulo ficou cego?", resposta: "Damasco", referencia_biblica: "Atos 9:3" },
  { numero: 45, nivel: "dificil", pergunta: "Qual evangelho cita o jovem que foge nu no momento que Jesus está sendo capturado?", resposta: "Marcos", referencia_biblica: "Marcos 14:51" },
  { numero: 46, nivel: "dificil", pergunta: "Qual é o nome do homem que construiu um altar em Betel?", resposta: "Jacó", referencia_biblica: "Gênesis 35:1-7" },
  { numero: 47, nivel: "dificil", pergunta: "Qual foi o desafio proposto por Elias aos profetas de Baal?", resposta: "Que cada um preparasse um altar e um sacrifício, sem acender fogo, e o deus que respondesse com fogo seria o verdadeiro Deus", referencia_biblica: "1 Reis 18:23-24 e v. 36-38" },
  { numero: 48, nivel: "dificil", pergunta: "Qual o nome do homem que foi arrebatado para outro lugar depois de batizar um eunuco?", resposta: "Filipe", referencia_biblica: "Atos 8:39" },
  { numero: 49, nivel: "dificil", pergunta: "Qual é o nome do homem que julgou entre duas mulheres que alegavam ser a mãe do mesmo bebê?", resposta: "Salomão", referencia_biblica: "1 Reis 3:23-24" },
  { numero: 50, nivel: "dificil", pergunta: "Quem foi o homem que liderou a reconstrução dos muros de Jerusalém?", resposta: "Neemias", referencia_biblica: "Neemias 2:11-17" },

  // ===== EXPERT =====
  { numero: 1, nivel: "expert", pergunta: "Quem foi o primeiro rei de Judá após a divisão do reino?", resposta: "Roboão", referencia_biblica: "1 Reis 14:21" },
  { numero: 2, nivel: "expert", pergunta: "Em Apocalipse, quantas estrelas estão na mão direita de Cristo?", resposta: "Sete estrelas", referencia_biblica: "Apocalipse 1:16-20" },
  { numero: 3, nivel: "expert", pergunta: "Qual era a profissão de Lídia, a primeira convertida europeia?", resposta: "Vendedora de Púrpura", referencia_biblica: "Atos 16:14-15" },
  { numero: 4, nivel: "expert", pergunta: "Quem era o sumo sacerdote de Israel quando Jesus foi julgado?", resposta: "Caifás", referencia_biblica: "Mateus 26:57" },
  { numero: 5, nivel: "expert", pergunta: "Qual é o nome da montanha onde Jesus deu o Sermão da Montanha?", resposta: "Conhecido como Monte das Bem-Aventuranças", referencia_biblica: "Mateus 5:1" },
  { numero: 6, nivel: "expert", pergunta: "Qual é o quinto mandamento?", resposta: "Honrar pai e mãe", referencia_biblica: "Êxodo 20:12" },
  { numero: 7, nivel: "expert", pergunta: "Em que ilha Paulo foi picado por uma serpente venenosa mas sobreviveu?", resposta: "Malta", referencia_biblica: "Atos 28:1-4" },
  { numero: 8, nivel: "expert", pergunta: "Quem foi o servo do sumo sacerdote que teve sua orelha cortada por um discípulo?", resposta: "Malco", referencia_biblica: "João 18:10" },
  { numero: 9, nivel: "expert", pergunta: "Quem foi o primeiro juiz de Israel?", resposta: "Otniel", referencia_biblica: "Juízes 3:7-11" },
  { numero: 10, nivel: "expert", pergunta: "Qual o nome do rei assírio que atacou Judá no tempo de Ezequias?", resposta: "Senaqueribe", referencia_biblica: "2 Reis 18:13" },
  { numero: 11, nivel: "expert", pergunta: "Quem era o rei de Tiro que enviou materiais para a construção do Templo de Salomão?", resposta: "Hirão", referencia_biblica: "2 Crônicas 2:3" },
  { numero: 12, nivel: "expert", pergunta: "Quem era o sumo sacerdote quando Israel capturou a Arca da Aliança?", resposta: "Eli", referencia_biblica: "1 Samuel 4:13" },
  { numero: 13, nivel: "expert", pergunta: "Quem era o comandante do exército de Israel que foi assassinado por Joabe?", resposta: "Abner", referencia_biblica: "2 Samuel 3:30" },
  { numero: 14, nivel: "expert", pergunta: "Quem foi o avô de Davi?", resposta: "Obede", referencia_biblica: "Rute 4:22" },
  { numero: 15, nivel: "expert", pergunta: "Quantos anos Moisés viveu no Egito antes de fugir para Midiã, após matar um egípcio?", resposta: "40 anos", referencia_biblica: "Atos 7:23" },
  { numero: 16, nivel: "expert", pergunta: "Quem foi o profeta que trouxe uma mensagem de Deus a Davi sobre a construção do templo?", resposta: "Natã", referencia_biblica: "2 Samuel 7:17" },
  { numero: 17, nivel: "expert", pergunta: "Qual é o nome do monte onde Elias desafiou os profetas de Baal?", resposta: "Monte Carmelo", referencia_biblica: "1 Reis 18:19" },
  { numero: 18, nivel: "expert", pergunta: "Qual rei estabeleceu as maiores conquistas militares de Israel, expandindo seu território?", resposta: "Davi", referencia_biblica: "2 Samuel 8:6" },
  { numero: 19, nivel: "expert", pergunta: "Quem foram os 3 homens que se rebelaram contra a liderança de Moisés e Arão, resultando em uma punição divina com a terra se abrindo e os engolindo?", resposta: "Corá, Datã e Abirão", referencia_biblica: "Números 16:26-27" },
  { numero: 20, nivel: "expert", pergunta: "Cite 3 igrejas das 7 igrejas mencionadas no livro de Apocalipse", resposta: "Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia", referencia_biblica: "Apocalipse 1:11" },
  { numero: 21, nivel: "expert", pergunta: "Quem era o fariseu e membro do Sinédrio que buscou Jesus à noite para uma conversa sobre o Reino de Deus?", resposta: "Nicodemos", referencia_biblica: "João 3:1-2" },
  { numero: 22, nivel: "expert", pergunta: "Quem foi o homem rico que buscou o corpo de Jesus para sepultá-lo em um túmulo novo?", resposta: "José de Arimateia", referencia_biblica: "Mateus 27:57-60" },
  { numero: 23, nivel: "expert", pergunta: "Qual rei teve sua vida estendida por 15 anos após orar a Deus?", resposta: "Ezequias", referencia_biblica: "2 Reis 20:1-6" },
  { numero: 24, nivel: "expert", pergunta: "Qual personagem do Antigo Testamento foi rei e sacerdote ao mesmo tempo?", resposta: "Melquisedeque", referencia_biblica: "Gênesis 14:18" },
  { numero: 25, nivel: "expert", pergunta: "Quem era o governador romano que ouviu a defesa de Paulo em Cesaréia?", resposta: "Félix", referencia_biblica: "Atos 24:22-24" },
  { numero: 26, nivel: "expert", pergunta: "Quais foram os dois nomes indicados para substituir Judas Iscariotes como apóstolo?", resposta: "José, chamado Barsabás, e Matias", referencia_biblica: "Atos 1:23" },
  { numero: 27, nivel: "expert", pergunta: "Adão viveu ao todo quantos anos?", resposta: "930 anos", referencia_biblica: "Gênesis 5:5" },
  { numero: 28, nivel: "expert", pergunta: "Qual a mulher que acolheu o seu inimigo e depois o matou?", resposta: "Jael", referencia_biblica: "Juízes 4:18-21" },
  { numero: 29, nivel: "expert", pergunta: "Balaão foi chamado por quem para amaldiçoar o povo de Israel?", resposta: "Balaque", referencia_biblica: "Números 22:4-6" },
  { numero: 30, nivel: "expert", pergunta: "Sofonias foi profeta durante qual reinado?", resposta: "Josias, rei de Judá", referencia_biblica: "Sofonias 1:1" },
  { numero: 31, nivel: "expert", pergunta: "Que povo recebeu Paulo com grande interesse, e examinou as Escrituras, para ver se tudo era verdade?", resposta: "Os bereanos", referencia_biblica: "Atos 17:10-11" },
  { numero: 32, nivel: "expert", pergunta: "Quem foi o rei que teve uma festa que durou seis meses?", resposta: "Assuero (Xerxes)", referencia_biblica: "Ester 1:3-4" },
  { numero: 33, nivel: "expert", pergunta: "O que houve quando o Cordeiro quebrou o último selo?", resposta: "Houve silêncio nos céus cerca de meia hora", referencia_biblica: "Apocalipse 8:1" },
  { numero: 34, nivel: "expert", pergunta: "Qual é o nome do monte onde Moisés viu a sarça ardente?", resposta: "Horebe", referencia_biblica: "Êxodo 3:1" },
  { numero: 35, nivel: "expert", pergunta: "Quantos anos os Israelitas ficaram no Egito?", resposta: "430 anos", referencia_biblica: "Êxodo 12:40-41" },
  { numero: 36, nivel: "expert", pergunta: "Qual sinal Deus deu a Ezequias para confirmar sua cura?", resposta: "A sombra retrocedeu dez graus no relógio de Acaz", referencia_biblica: "2 Reis 20:8-11" },
  { numero: 37, nivel: "expert", pergunta: "Qual é o nome da mulher que foi a primeira missionária na Europa?", resposta: "Lídia", referencia_biblica: "Atos 16:14-15" },
  { numero: 38, nivel: "expert", pergunta: "Qual foi o motivo pelo qual Davi não pôde construir o templo do Senhor, mesmo desejando fazê-lo?", resposta: "Porque tinha derramado muito sangue e fez grandes guerras", referencia_biblica: "1 Crônicas 22:8" },
  { numero: 39, nivel: "expert", pergunta: "Quem foi o rei que destruiu os altares pagãos em Israel e Judá?", resposta: "Josias", referencia_biblica: "2 Reis 23:8" },
  { numero: 40, nivel: "expert", pergunta: "Quem foi o profeta que foi chamado para profetizar contra Nínive?", resposta: "Jonas", referencia_biblica: "Jonas 1:1-2" },
  { numero: 41, nivel: "expert", pergunta: "Qual o nome do rapaz que morreu durante a pregação de Paulo?", resposta: "Êutico", referencia_biblica: "Atos 20:9" },
  { numero: 42, nivel: "expert", pergunta: "Qual o nome da menina que voltou a vida através da oração do apóstolo Pedro?", resposta: 'Dorcas (ou em grego, "Tabita")', referencia_biblica: "Atos 9:36-42" },
  { numero: 43, nivel: "expert", pergunta: "Que objeto o profeta Eliseu fez flutuar no rio?", resposta: "Machado", referencia_biblica: "2 Reis 6:6" },
  { numero: 44, nivel: "expert", pergunta: "Qual rio se abriu para o povo de Israel atravessar após a morte de Moisés?", resposta: "Rio Jordão", referencia_biblica: "Josué 3:14-17" },
  { numero: 45, nivel: "expert", pergunta: "Quem foi o profeta que falou sobre a vinda do Messias como um servo sofredor?", resposta: "Isaías", referencia_biblica: "Isaías 53" },
  { numero: 46, nivel: "expert", pergunta: "Quem foi o discípulo que viajou com Paulo em sua segunda viagem missionária?", resposta: "Silas", referencia_biblica: "Atos 15:40-41" },
  { numero: 47, nivel: "expert", pergunta: "Quem foi o rei que quase matou seu próprio filho por ele ter comido mel?", resposta: "Saul", referencia_biblica: "1 Samuel 14:43-44" },
  { numero: 48, nivel: "expert", pergunta: "De que material era o muro da Nova Jerusalém descrito em Apocalipse?", resposta: "Jaspe", referencia_biblica: "Apocalipse 21:18" },
  { numero: 49, nivel: "expert", pergunta: "Como era o formato da cidade Nova Jerusalém descrito em Apocalipse?", resposta: "Quadrado", referencia_biblica: "Apocalipse 21:16" },
  { numero: 50, nivel: "expert", pergunta: "Quem era o comandante do exército do rei da Síria, que foi curado de lepra por mergulhar sete vezes no rio Jordão?", resposta: "Naamã", referencia_biblica: "2 Reis 5:14" },
];
